### PR TITLE
link swift-nio-extras in docs

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@weissi Seems like the Swift 5.2 tests are fundamentally broken here too.

**Comment by weissi** [comment]
@Lukasa this is the problem:

```
18:13:48 .FileNotFoundError: [Errno 2] No such file or directory: './docker/docker-compose.1804.52.yaml'
```

needs a PR like https://github.com/apple/swift-nio-extras/pull/86

**Comment by Lukasa** [comment]
5.3 compiler crash is expected

**Pull request merged**
