### PR TITLE
Remove support for Swift 5.0 and 5.1

### PR DESCRIPTION
**Pull request by Davidde94**
Changes made:

- [ ] Removed CI config for 5.0 ad 5.1
- [ ] Changed 5.2 to be based on 16.04 so we have some coverage there
- [ ] Converted Package.swift to the latest syntax
- [ ] Added a description to supported Swift versions in the README

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot add to allowlist

**Comment by Davidde94** [comment]
@yim-lee could you do your thing here also please? Not many to go!

- [ ] Remove the 5.0 and 5.1 jobs
- [ ] Update the 5.2 job to use 16.04
- [ ] Update the API breakage to be based on the Swift 5.4 Ubuntu 20.04 image

**Comment by yim-lee** [comment]
@swift-nio-bot test this please

**Comment by yim-lee** [comment]
@swift-nio-bot test this please

**Comment by yim-lee** [comment]
@Davidde94 CI changes done.

**Comment by Davidde94** [comment]
@yim-lee many thanks :)

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
