### PR TITLE
Fix command to generate tests on Linux

### LINKED ISSUE #7: Incorrect instructions for ruby file to generate Linux tests
The [CONTRIBUTING.md](https://github.com/apple/swift-nio-http2/blob/master/CONTRIBUTING.md) states that `ruby generate_linux_tests.rb` should used to generate the tests for Linux in the root directory. The file isn't in the root directory

### PR DESCRIPTION
**Pull request by 0xTim**
Resolves #7

### CODE REVIEW

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
If that doesn't pass, it means I broke it. :(

**Comment by Lukasa** [comment]
Should be unblocked by the merge of #9.

**Comment by 0xTim** [comment]
@Lukasa done

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Nicely done, thanks @0xTim!

**Pull request merged**
