### PR TITLE
docker setup for main nightlies

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Review by PeterAdams-A — APPROVED** [review]
Seems sensible.

**Review by Lukasa — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@weissi Seems like the nightly is failing due to TSAN being busted, want to disable it?

**Comment by tomerd** [comment]
> @weissi Seems like the nightly is failing due to TSAN being busted, want to disable it?

this is an issue we have on all docker images > 16.04 on the kernel we run on CI hosts. yet to figure it out :/

**Comment by weissi** [comment]
> this is an issue we have on all ubuntu docker images > 16.04 on the kernel we run on CI hosts. yet to figure it out :/

@tomerd I think on 5.4 it's even worse and it doesn't even work on 16.04, I think I tried with NIO...

**Review by Lukasa — CHANGES_REQUESTED** [review]
This needs substantial changes. The image name is wrong (you have `swift-nio` but it should be `swift-nio-http2`, and you're missing a `h2spec_version` directive in `runtime-setup`.

**Comment by weissi** [comment]
@Lukasa sorry this took so long, missed your comments. Updated

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
