### PR TITLE
Add SECURITY.md

### PR DESCRIPTION
**Pull request by glbrntt**

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@tomerd What's up with CI here?

**Comment by glbrntt** [comment]
> @tomerd What's up with CI here?

Looks like alloc limits, presumably from NIO 2.26, I'll fix these up.

**Pull request merged**
