### PR TITLE
[nghttp2] Forward `channelInactive` events to the child channels.

### PR DESCRIPTION
**Pull request by t089**
Not sure if you are still interested in patches for the nghttp2 support branch. Some people might be brave enough to be still using it... ;)

I noticed that stale/disconnected connections never fail/disconnect the child channels. The reason seems to be that the multiplexer does not forward `channelIncactive` events. This PR fixes this.

If you _really want_ I can add an test for this...

### CODE REVIEW

**Comment by Lukasa** [comment]
@weissi Do we think we should take patches to this branch? My default position is "unless they're security patches, no", but I'm interested in your thoughts here.

**Comment by normanmaurer** [comment]
@weissi @Lukasa not sure it matters much but we did the same for Netty 3 while it was EOL. We took some patches but did not do a release. This just helped people to roll their own releases.

**Comment by t089** [comment]
@weissi yes, for the time being, it is used in production for a service that delivers push notifications. There is a dependency on vapor 3 that we have to get rid off. Then we will switch to NIO2 land. Hopefully soon. So for now I'm just using my fork that has the fix, but since it was such a small detail I thought a patch might still be a good idea?

**Comment by MrMage** [comment]
> @weissi yes, for the time being, it is used in production for a service that delivers push notifications. There is a dependency on vapor 3 that we have to get rid off. Then we will switch to NIO2 land. Hopefully soon. So for now I'm just using my fork that has the fix, but since it was such a small detail I thought a patch might still be a good idea?

FYI, I am in the same spot. That's why I had to file #50 a while ago, but that was indeed a bugfix.

**Comment by weissi** [comment]
Thanks @normanmaurer , @t089 , and @MrMage. I'll then have the following proposal, note this is my personal opinion and need to check with @normanmaurer / @Lukasa: I'd propose that we accept _SemVer patch_ PRs that come with unit tests and fulfil the usual quality bar. Assuming that sounds good, I would also be happy for @t089 & @MrMage to do the release management in the way that they do some validation testing and once that looks good, they can send us a SHA and we (Cory/I) issue a new tag `0.2.(n+1)` for that SHA. What does everybody think about that?

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Works for me.

**Comment by MrMage** [comment]
Sounds good to me!

**Comment by weissi** [comment]
@t089 if you wouldn't mind adding a test here, then we can get this in. I'll make a PR to get the CI fixed (the docker file isn't quite right in this branch).

**Comment by weissi** [comment]
#147 should fix the CI

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by t089** [comment]
@weissi Thanks I will come back with a test 👨‍⚕

**Comment by weissi** [comment]
perf test fail

```
08:54:16 Test Case 'HuffmanCodingTests.testBasicDecodingPerformance' started at 2019-07-19 08:54:16.178
08:54:36 /code/Tests/NIOHPACKTests/HuffmanCodingTests.swift:153: Test Case 'HuffmanCodingTests.testBasicDecodingPerformance' measured [Time, seconds] average: 1.828, relative standard deviation: 15.830%, values: [1.833453, 1.564175, 1.588911, 1.380998, 1.848516, 2.027521, 2.174065, 1.831311, 2.328512, 1.700139], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
08:54:36 /code/Tests/NIOHPACKTests/HuffmanCodingTests.swift:153: error: HuffmanCodingTests.testBasicDecodingPerformance : failed: The relative standard deviation of the measurements is 15.830% which is higher than the max allowed of 10.000%.
08:54:36 Test Case 'HuffmanCodingTests.testBasicDecodingPerformance' failed (20.213 seconds)
```

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by t089** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by t089** [comment]
[Test](https://github.com/apple/swift-nio-http2/blob/2d1e014981d6fb269dfbbf2d957e6cdc7fe7385d/Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift#L394) added. Let me know if there is something else I can do.

**Pull request merged**
